<?php

return [
    'name' => ['姓名', '名称'],
    'given' => ['名字'],
    'last_name' => ['姓氏'],
    'email' => ['邮箱', '电子邮箱', '电子邮件', '邮箱地址'],
    'phone' => ['电话', '电话号码', '联系电话'],
    'mobile' => ['手机', '手机号', '手机号码'],
    'city' => ['城市'],
    'country' => ['国家'],
    'address' => ['地址', '详细地址'],
    'street' => ['街道'],
    'postal_code' => ['邮编', '邮政编码'],
    'company' => ['公司', '公司名称'],
    'price' => ['价格', '单价'],
    'quantity' => ['数量'],
    'description' => ['描述'],
    'title' => ['标题'],
    'sku' => ['货号'],
    'category' => ['类别', '分类', '类目'],
    'notes' => ['备注'],
    'comment' => ['评论'],
    'status' => ['状态'],
    'date_of_birth' => ['出生日期', '生日'],
];
