<?php

return [
    'name' => ['姓名', '名稱'],
    'given' => ['名字'],
    'last_name' => ['姓氏'],
    'email' => ['電郵', '電郵地址', '電子郵件'],
    'phone' => ['電話', '電話號碼', '聯絡電話'],
    'mobile' => ['手機', '手提電話', '流動電話'],
    'city' => ['城市'],
    'country' => ['國家', '國家/地區'],
    'address' => ['地址'],
    'street' => ['街道'],
    'postal_code' => ['郵政編碼'],
    'company' => ['公司', '公司名稱'],
    'price' => ['價格', '單價', '價錢'],
    'quantity' => ['數量'],
    'description' => ['描述'],
    'title' => ['標題'],
    'sku' => ['貨號'],
    'category' => ['類別', '分類'],
    'notes' => ['備註'],
    'comment' => ['評論'],
    'status' => ['狀態'],
    'date_of_birth' => ['出生日期', '生日'],
];
